=== bkil/liquid-war-5/doc/xml/file.dtd
<!ELEMENT file (chap*|(text|code|list)*)>
<!ATTLIST file title CDATA "">
<!ELEMENT chap (part*|(text|code|list)*)>
<!ATTLIST chap title CDATA "">
<!ELEMENT part ((text|code|list)*)>
<!ATTLIST part title CDATA "">
<!ELEMENT text (#PCDATA)>
<!ELEMENT list (elem+)>
<!ELEMENT elem (#PCDATA)>
<!ELEMENT code (#PCDATA)>

=== bkil/liquid-war-5/doc/xml/userlevels.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE file SYSTEM "file.dtd">
<file title="User levels">

  <chap title="A piece of advice"> 
    <text>
      You can use your own levels whith Liquid War 5.
      The only thing you have to do is to put your own 256-colors vbitmap files
      in a special directory, and the program will use them.
      Currently, BMP, LBM, PCX, and TGA files are supported.
      It is a good thing to use 256 colors bitmaps,
      for they waste less disk space than truecolor bitmaps,
      and Liquid War 5 converts all bitmaps to 32 colors bitmaps.
      Additionnally, truecolor bitmaps might cause the DOS version
      to crash randomly...
      2-color bitmaps will also cause the program to crash.
      I warned you!
    </text>
    <text>
      The best thing you can do to create your user levels
      is to have a look at the few user files I put in the .zip file
      and try at first to do something that looks about the same!
    </text>
  </chap>

  <chap title="Maps">
    <text> 
      Liquid War 5 does many checks on user levels
      and is much safer than Liquid War 3.
      Still, try and help the program not to crash, if possible. 
    </text>
    <text>
      Liquid War considers that dark colors are walls
      and bright colors are associated to the playable area.
      So you can draw your walls in black, dark blue, etc...
      And the rest of the map can be of any bright color
      such as white or yellow.
    </text>
    <text>
      You can draw a small map on a big bitmap,
      as long as you use a bright background color.
      Liquid War will autodetect the range of your map
      and add the border line if necessary.
    </text>
    <text>
      Liquid War re-orders all the maps,
      so that the smallest ones are on the left
      and the most complicated ones on the right
      when you choose them with the slider
      in the "map" menu.
      So if you can't find the map you just draw,
      don't worry, it is probably just mixed with
      the levels from the .dat file.
    </text>
    <text>
      The default path for maps is "custom\map\" on windows, and
      "/usr/local/share/games/liquidwar/map" on GNU/Linux.
    </text>
  </chap>

  <chap title="Textures">
    <text> 
      All you have to do is put a bitmap in the default directory
      which is "custom\texture\" on windows, and 
      "/usr/local/share/games/liquidwar/texture" on GNU/Linux.
    </text>
  </chap>

  <chap title="Textures">
    <text>
      As of Liquid War 5.6.x, it's possible to associate a map with
      a texture. All you need is to call the maps with the same name
      (case is important, lowercase recommendend...). Look at the
      "meditate" custom map which is shipped with Liquid War for
      instance.
    </text>
    <text>
      This also works with internal builtin maps (those stored in
      the datafile) so for instance if you name a custom texture
      "world1.bmp" it will automatically be associated to the builtin
      map world1 (to figure out internal names you have to unpack
      the source distribution and look in the ./data directory).
      This also works the other way, if you name a map "wood2.bmp"
      it will be automatically associated with the builtin texture
      wood2.
    </text>
    <text>
      Associating a texture with a map requires more work than
      designing a simple map, but the results is usually much
      nicer. See the "Kasper - ..." series of maps for instance.
    </text>
  </chap>

  <chap title="Send your levels">
    <text>
      Maybe you will find that the original levels are ugly and unplayable.
      Well, if you have made user levels and think they are great,
      just send them to the Liquid War user mailing list.
      Please use only 256 colors bitmap and zip them before sending them,
      or else they might be blocked by my provider...
    </text>
    <text>
      As of today, dozens of user maps have already been included
      in Liquid War, this is very nice for it happens that every
      map designer has his own personnal tastes, so the maps all
      look different.
    </text>
    <text>
      Still, to be included in Liquid War's mainstream distribution,
      your maps will need to be placed under the terms of the 
      GNU General Public License, or at least a compatible license.
      You should have received a copy of this license with Liquid War
      anyway. Read it 8-)
    </text>
    <text>
      Of course, you can use *any* map when playing. You can even
      play with a bitmap you got from a proprietary source - such a
      proprietary game you bought for instance - but the point
      is that I can't - and you can't either - distribute such a map
      along with Liquid War.
    </text>
    <text>
      However, this is enough legal boring stuff! What you should keep
      in mind is that I'm always happy when I receive maps from
      players, and it's a pleasure for me to include them in the
      mainstream distribution.
    </text>
  </chap>

</file>

=== bkil/liquid-war-5/doc/xml/parameters.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE file SYSTEM "file.dtd">
<file title="Command line parameters">
  
  <chap title="Introduction"> 
    <text>
      When you launch Liquid War 5, you can use command line options.
      If you have no problems launching Liquid War,
      this section should not interest you very much.
    </text>
    <text>
      You can use several options at the same time.
      The basic syntax for options looks like this:
    </text>
    <code>
      lw -option1 -option2 parameter2 -option3 parameter3 -option4 -option5
    </code>
    <text>
      Note that most of the options are legacy options which where usefull
      with the initial releases of Liquid War, when you had to run in a
      Windows DOS box, and when there were still plenty of 486 computers
      with only 8Mb ram...
    </text>
  </chap>

  <chap title="Version checking">
    <text>
      These are basic options which can be usefull to figure out
      which release of Liquid War is installed.
    </text>
    <list>
      <elem>
	"-v" : returns the version number of the program.
      </elem>
      <elem>
	"-h" : displays a short description and copyright information.
      </elem>
    </list>
  </chap>

  <chap title="Changing default paths">
    <text>
      Very usefull options, especially if you can not install Liquid War
      in default directories or want to put the game in a special place.
    </text>
    <list>
      <elem>
	"-cfg myconfigfile.cfg" : causes Liquid War to use the specified
	config file.
      </elem>
      <elem>
	"-dat mydatafilefile.dat" : causes Liquid War to use the specified
	datafile. This might be a very interesting option if you run
	Liquid War on a GNU/Linux box where you do not have root access and
	therefore can not put the datafile in /usr.
      </elem>
      <elem>
	"-map mycustommapdir" : causes Liquid War to use the specified
	directory as the user map directory. The user map directory
	is where you can put plain bitmaps to be used as maps.
      </elem>
      <elem>
	"-tex mycustomtexturedir" : causes Liquid War to use the specified
	directory as the user texture directory. The user texture directory
	is where you can put plain bitmaps to be used as textures.
      </elem>
      <elem>
	"-mid mycustommusicdir" : causes Liquid War to use the specified
	directory as the user music directory. Any midi file placed in this
	directory will be added to the list of available musics.
      </elem>
      <elem>
	"-server myliquidwarserverfile" : causes Liquid War to use the specified
	file as the server executable. This option has no effect for now since
	the server is not launched by the client.
      </elem>
      <elem>
	"-mapgen mylwmapgenfile" : causes Liquid War to use the specified
	file as the "lwmapgen" executable. "lwmapgen" is an utility by David Redick
	which generates random maps automatically for Liquid War. You might wish
	to change this option if random map generation does not work for some reason,
	or if you want to use your own map generator.
      </elem>
    </list>
  </chap>

  <chap title="Troubleshooting switches">
    <text>
      These options give you control on how Liquid War treats
      initialisation errors, how much memory it should reserve,
      what kind of video mode sit should not choose etc...
    </text>
    <list>
      <elem>
	"-vga" :
	This option forces Liquid War to use your video card
	as if it was only a basic VGA card. 
	This option is required if you play Liquid War from Windows NT.
      </elem>
      <elem>
	"-no400300" :
	This option disables the VGA 400x300 video mode.
	I created this options for I know that some video cards/monitors
	don't support the 400x300 mode.
      </elem>
      <elem>
	"-silent" :
	With this option, Liquid War will not play any sound.
	It will not search for any sound card.
	This can be interesting if you don't have any sound card
	or if Liquid War doesn't handle your card correctly.
      </elem>
      <elem>
	"-nowater" :
	Causes Liquid War not to load any water sound.
	Use this if Liquid War runs short of memory,
	and you should gain about 850kb.
      </elem>
      <elem>
	"-nosfx" :
	Causes Liquid War not to load any sound fx.
	Use this if Liquid War runs short of memory,
	and you should gain about 150kb.
      </elem>
      <elem>
	"-nomusic" :
	Causes Liquid War not to load any midi music.
      </elem>
      <elem>
	"-mem n" :
	The parameter "n" sets the amount of memory (in Mb)
	Liquid War will allocate to do all its calculus.
	If this number is too small, you won't be able to play
	on all the levels.
	If it is too high, Liquid War may not start at all
	or crash while you are playing.
	The default value is 8.
	If you play Liquid War from Windows and Liquid War
	refuses to run because this parameter is too high,
	then try and give more dpmi memory to Liquid War.
      </elem>
      <elem>
	"-nojoy" :
	This option disables joystick support.
      </elem>
      <elem>
	"-noback" :
	Causes Liquid War not to load the background image.
	Use this if Liquid War runs short of memory,
	and you should gain about 300kb.
      </elem>
      <elem>
	"-notex" :
	Causes Liquid War not to load any texture.
	Use this if Liquid War runs short of memory,
	and you should gain about 750kb.
      </elem>
      <elem>
	"-auto" :
	If you set this option, Liquid War won't generate
	any error while allocating memory or loading data.     
      </elem>
      <elem>
	"-safe" :
	With this option, you will play with a very reduced
	version of Liquid War. It looks rather ugly but
	should work in a DOS box with only 4Mb of DPMI memory.
	Use this if you experience serious memory or device problems.
	If Liquid War doesn't start with this option turned on,
	I really don't think I can do anything for you...
      </elem>
      <elem>
	"-nice" :
	With this option, Liquid War will use a mode which
	is between the default mode and the "safe" mode.
      </elem>
      <elem>
	"-check" :
	With this option, Liquid War will stop as soon as it detects
	something strange while initializing.
      </elem>
      <elem>
	"-stop" :
	If you set this option, Liquid War will prompt you for a key
	when the init process is completed.
      </elem>
      <elem>
	"-c" :
	This is a weird option, if you turn it on,
	the game will only use fonctions which are programmed in C langage.
	The default behaviour is to use some functions I rewrote
	in assembly langage, so that the game is a little faster.
      </elem>
    </list>
  </chap>
  
  <chap title="Debug options">
    <text>
      These options are usefull if you want to debug the game and
      trace what's happening.
    </text>
    <list>
      <elem>
	"-netlog" :
	Dumps all the network traffic on the standard output. This
	can help finding problems when trying to connect to the server
	in a network game.
      </elem>
    </list>
  </chap>
  
  <chap title="Server options">
    <text>
      The server command line options are described in the section
      which deals which network games in general. IMHO you need to
      understand how network works in LW before trying to tweak
      the server 8-)
    </text>
  </chap>

  <chap title="Other options">
    <text>
      Everything else 8-)
    </text>
    <list>
      <elem>
	"-capture" :
	Activates the capture mode. In this mode, the game will
	dump a .bmp file on the disk several times per second, which
	is usefull if you want to create an mpeg movie of your game
	session afterwards. You can also activate this mode interactively
	by pressing F9 within the game.
      </elem>
      <elem>
	"-metaserver url" : redefines the URL of the meta-server.
	Usefull if you want to use your own meta-server.
      </elem>
      <elem>
	"-nobeep" :
	Disables the system beeps that the application might fire.
	These beeps are mostly used on the server to notify clients connections.
      </elem>
      <elem>
	"-tombola" :
	Activates a special mode where scores are not displayed 
	normally. Instead, the game displays 3 random numbers between 1 - 500.
      </elem>
    </list>
  </chap>
  
  <chap title="lwmapgen options">
    <text>
      The external lwmapgen program by David Redick accepts a
      number of command line options. You can type:
    </text>
    <code>
liquidwar-mapgen --help
    </code>
    <text>
      to get a list of all available options under UNIX. Under Windows
      the command would be:
    </text>
    <code>
lwwinmap --help
    </code>
    <text>
      Note that lwmapgen is called automatically by Liquid War
      when you click on the "Random map" button.
    </text>
    <text>
      The idea behind lwmapgen is that you choose a function which
      sets the type of map generated, and then pass various arguments
      to this function. If you do not explicitly choose a function, one
      will be picked up for you randomly, and all other parameters will
      use default values.
    </text>
    <text>
      The most usefull and common options are:
    </text>
    <list>
      <elem>
	"--help" :
	displays help.
      </elem>
      <elem>
	"--out filename" :
	save bitmap to filename.
      </elem>
      <elem>
	"--size n" :
	bitmap size (an integer between 0 and 5).
      </elem>
      <elem>
	"--list" :
	list all available functions.
      </elem>
      <elem>
	"--function function_name" :
	which function to use.
      </elem>
    </list>
    <text>
      Here's a typical use of lwmapgen:
    </text>
    <code>
liquidwar-mapgen --size 3 --function hole --out test.bmp
    </code>
  </chap>

</file>

=== bkil/liquid-war-5/doc/xml/authors.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE file SYSTEM "file:xml/file.dtd">
<file title="Authors">

  <chap title="Thom-Thom">
    <text>
      Liquid War rules have been invented by
      Thomas Colcombet.
    </text>
    <text>
      He was trying to find algorithms to find the shortest path
      from one point to another, and found the Liquid War
      algorithm. Then it came to his mind that a game could
      be build upon this algorithm, and Liquid War was born.
      He programmed the first two versions of Liquid War
      using Borland Pascal for DOS, and gave me some information
      about the algorithm so that I could re-program it.
    </text>
  </chap>

  <chap title="U-Foot">
    <text>
      I'm the guy who programmed the latest versions of Liquid War.
      I enhanced the algorithms, and did quite a bunch of work
      to have the game playable by (almost) anyone, that's to
      say create a correct GUI.
    </text>
    <text>
      If you want to join me, here's all the information you'll ever need:
    </text>
    <code>
Christian Mauduit

E-mail: "ufoot@ufoot.org" 
Web site: "http://www.ufoot.org"

GnuPG public key: FD409E94 - "http://www.ufoot.org/gnupg.pub"
GnuPG fingerprint: 4762 1EBA 5FA3 E62F 299C  B0BB DE3F 2BCD FD40 9E94

Snail mail: 32 rue Jean Moulin  95100 Argenteuil  FRANCE
    </code>
  </chap>

  <chap title="Other contributors">
    <text>
      As Liquid War is now free software, protected by the GPL,
      anyone is allowed to view, edit, modify, re-compile
      the source code, and distribute it, as long as Liquid 
      War is still distributed under the GPL.
    </text>
    <text>
      Here's a list of the contributors:
    </text>
    <list>
      <elem>
	Alstar: drew a map, which is now included in the main distribution.
      </elem>
      <elem>
        Peter Wang: ported Liquid War to GNU/Linux.
      </elem>
      <elem>
	Cort Danger Stratton : helped me setting up network support.
      </elem>
      <elem>
	Tim Chadburn : wrote midi files for the game. His contribution has
	been truely appreciated since it's rather hard to find GNU GPL
	compliant artwork. He also wrote documentation and helped with
	midi support in general.
      </elem>
      <elem>
        Jan Gretschuskin : contributed 11 maps, and made the German
	translation. So if you run Liquid War with German menus, you
	know who you have to thank -> Jan! 8-) 
	Also do not forget to visit "http://www.game-factor.de"
      </elem>
      <elem>
        Mouse : contributed a map.
      </elem>
      <elem>
        Rene Stach : drew 3 maps.
      </elem>
      <elem>
	Roderick Schertler : implemented HTTP 1.1 support.
      </elem>
      <elem>
	Ryan D. Brown : ported Liquid War to Mac OS X.
      </elem>
      <elem>
	Eduard Bloch : maintained the Debian package, 
	and helped with German support.
      </elem>
      <elem>
	Michael Terry : provided a .desktop file for better integration
	with Gnome, KDE and other UNIX desktop environments.
      </elem>
      <elem>
	Kasper Hviid : contributed many maps, with their own
	textures, and made the Danish translation. Great work, also
	available on "http://levels.2v1.cz/index.html"
      </elem>
      <elem>
	David Redick : wrote an external random map generator,
	available on "http://xdavidx.sqrville.org/lwmapgen/index.html"
      </elem>
      <elem>
	Alexandre Pineau : maintains the Debian package.
      </elem>
      <elem>
	Michael Wagner : translated the web site in German.
      </elem>
      <elem>
	Peter Williams : fixed the "too many opened socket" server bug.
      </elem>
      <elem>
	Jan Samohyl : submitted strategy tips.
      </elem>
      <elem>
	Gavin : wrote the Liquid War fanfic.
      </elem>
      <elem>
	Dave Vasilevsky : fixed the Mac OS X port.
      </elem>
      <elem>
	2 of omega : contributed a map.
      </elem>
      <elem>
	666-REFIZUL-666 : created many maps (distributed separately).
      </elem>
      <elem>
	Thomas Klausner : fixed Makefile for FreeBSD
      </elem>
      <elem>
	Joan Dolc : helped with Mac OS/X port
      </elem>
    </list>
    <text>
      Many other people helped me by submitting bug reports and patches,
      and I want to thank them for their precious help. Thanks to all the
      Debian people too, who nicely maintain the Liquid War .deb package.
    </text>
  </chap>

</file>

=== bkil/liquid-war-5/doc/xml/mailinglists.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE file SYSTEM "file:xml/file.dtd">
<file title="Mailing lists">

  <chap title="liquidwar-user">
    <part title="Description">
      <text>
	This list is for general discussions about Liquid War.
	Here you can make suggestions, submit bug reports, 
	ask for help, find players, etc...	
	Basically, any question or remark which concerns the game
	is welcomed on this list.
      </text>
    </part>
    <part title="Practical informations">
      <text>
	You can't send messages to the list without subscribing.
	The only reason for this is that it's one of the only 
	way to block spam efficiently.
	I first thought it could be OK to allow anyone to post, but
	liquidwar-user seems to have be harvested by robots, so now I
	need to restrict posters. 
	However, I insist on the fact that anyone can subscribe, and
	the subscription to the list is not moderated.
	So if you are a human being and not a stupid spam robot, 
	you're welcome on the list 8-)
      </text>
      <text>
	Here's a list of usefull URLs:
      </text>
      <list>
	<elem>
	  To (un)subscribe: "http://mail.nongnu.org/mailman/listinfo/liquidwar-user"
	</elem>
	<elem>	  
	  To consult archives: "http://mail.nongnu.org/pipermail/liquidwar-user/"
	</elem>
	<elem>	  
	  To post on the list: "liquidwar-user@nongnu.org"
	</elem>	  
      </list>
    </part>
  </chap>

  <chap title="Chat and IRC">
    <part title="Web-based chat-box">
      <text>
	I have have set up a web-based chat-box which is accessible here:
	"http://www.ufoot.org/liquidwar/v5/metaserver.php"
      </text>
      <text>
	It's not as good as a good old IRC channel but not everybody can
	use IRC (because of firewalls and the likes), 
	and I like the idea that people
	can chat and have the list of available servers in one single
	web page.
      </text>
    </part>
    <part title="IRC channels">
      <text>
	I personnally spend some time on irc.freenode.net so you
	might use it to find other players - though I'm not really
	an IRC addict... ...not yet at least!
      </text>
      <text>
	Here are the channels I recommend:
      </text>
      <list>
	<elem>
	  #liquidwar : Liquid War dedicated channel,
	  to find players and chat while playing.
	</elem>
	<elem>
	  #netgame_players : general channel for players 
	  who want to play Internet games
	  - Free Software and/or Open Source games of course, 
	  we're on freenode.net 8-)
	</elem>
      </list>
    </part>
  </chap>

</file>
