=== bkil/liquid-war-5/doc/xml/file.dtd
<!ELEMENT file (chap*|(text|code|list)*)>
<!ATTLIST file title CDATA "">
<!ELEMENT chap (part*|(text|code|list)*)>
<!ATTLIST chap title CDATA "">
<!ELEMENT part ((text|code|list)*)>
<!ATTLIST part title CDATA "">
<!ELEMENT text (#PCDATA)>
<!ELEMENT list (elem+)>
<!ELEMENT elem (#PCDATA)>
<!ELEMENT code (#PCDATA)>

=== bkil/liquid-war-5/doc/xml/wip.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE file SYSTEM "file:xml/file.dtd">
<file title="Work in progress">
  <chap title="Note on releases">
    <text>
      Whenever Liquid War is released, I usually pass
      the good news to Freshmeat
      ( "http://freshmeat.net/projects/liquidwar/" ).
      Then all releases are accessible from the main
      download page, which is "http://www.ufoot.org/liquidwar/v5/download".
    </text>
    <text>
      Releasing the game takes time, for I want all binaries
      to install properly and sources to compile cleanly.
      Therefore there might be some delay before the time
      coding is over and the time a release is actually
      ready.
      So for impatients and/or for people who need to test
      out the very latest versions (eg someone who wants
      to compile the game on a new platform), it's possible
      to access the source repository directly.
    </text>
  </chap>
  <chap title="About GNU Arch">
    <text>
      I use GNU Arch (Tom Lord's Arch in fact, 
      "http://www.gnu.org/software/gnu-arch/" ) instead of the
      previously used CVS. Indeed, tla has some very fancy features
      such as signing patches with gpg, and I'm tired of suffering
      CVS limitations.
    </text>
    <text>
      So FYI the previously active CVS repositories, on Sourceforge
      and Savannah, are currently unmaintained.
    </text>
  </chap>
  <chap title="How to get latest releases">
    <list>
      <elem>
	Step 1: read the excellent Arch tutorial
	"http://regexps.srparish.net/www/tutorial/html/arch.html"
	if you are not familiar with tla. I admit there's
	a steep learning curve, but it's yet clear and understandable.
      </elem>
      <elem>
	Step 2: point on my repository, which is accessible (read-only) on
	"http://ufoot.hd.free.fr/depot/pub/2005-freesoftware/liquidwar/".
	Should this address move, try "http://ufoot.hd.free.fr/depot/pub/"
	and browse until you find Liquid War.
      </elem>
    </list>
    <text>
      Note that "http://ufoot.hd.free.fr" is a personnal web server
      located in my living room. It uses a simple DSL connection,
      so bandwidth won't be exceptionnally high, and it may suffer
      long and unexpected downtimes.
    </text>
    <text>
      If you are interested, I can open this repository in read/write
      mode, however one of the points of GNU Arch is that it allows
      cooperative developpement with multiple depots, so this isn't
      mandatory. And anyways, importing myself patches received
      by email has never been a real burden.
    </text>
  </chap>
</file>

=== bkil/liquid-war-5/doc/xml/rules.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE file SYSTEM "file:xml/file.dtd">
<file title="Rules">

  <chap title="The Liquid War concept">
    <text>
      Liquid War is a wargame. 
      But it is different from common wargames.    
    </text>
    <text>
      When playing Liquid War, one has to eat one's opponent.
      There can be from 2 to 6 players.
      There are no weapons, the only thing you have to do
      is to move a cursor in a 2-D battlefield.
      This cursor is followed by your army, which is composed
      by a great many little fighters.
      Fighters are represented by small colored squares.
      All the fighters who have the same color
      belong to the same team.
      One very often controls
      several thousands fighters at the same time.
      And when fighters from different teams meet, 
      they eat each other, it is as simple as that.
    </text>
  </chap>
  
  <chap title="How do teams react?">
    <text>
      Teams are composed of little fighters.
      These fighters all act independently, 
      so it can happen that one single fighters does something
      different from what all the other do.
    </text>
    <text>
      The main goal of these fighters is to reach the cursor you control. 
      And to do that, they are in a way quite clever,
      for they choose the shortest way to reach it.
      Check it if you want, but it is true, they *really*
      choose *the* shortest way to reach the cursor.
      That is the whole point with Liquid War.
    </text>
    <text>
      But these fighters are not perfect,
      so when they choose this shortest way,
      they do as if they were alone on the battlefield.
      That's to say that if there is a fighter blocking
      their way, they won't have the idea to choose
      another way, which is free from fighters but
      would have been longer otherwise.
      So fighters can be blocked.             
    </text>
  </chap>

  <chap title="Who eats whom?">
    <text>
      When two fighters from different team meet each other,
      they first try to avoid fighting, and they dodge. 
      But if there is no way for them to move,
      they get angry and attack the guy which is blocking them.
      Sometimes, they attack each other and both loose health.
      But it can happen that a fighter is attacked by
      another one, which is himself not attacked at all.
    </text>
    <text>
      Here is an example of this behaviour:
      A blue fighter and a red fighter both want to move to 
      their right, for that would be the shortest way
      to reach their cursor if there was nobody on the battlefield.
      But they are blocked by other fighters.
      If, for instance, the red fighter is on the right
      and the blue fighter on the left,
      it is the red fighter which will be eaten.
    </text>
    <text>
      When a fighter is attacked, he first looses health,
      that is to say that he gets darker.
      When his health reaches 0, his color changes
      and he becomes a member of the team by which
      he has been attacked.
      Therefore the number of fighters on the battlefield
      always remains the same.                           
    </text>
    <text>
      When fighters of a same team get stuck together
      and block each other, then they regenerate,
      that is to say that they get brighter.        
    </text>
    <text>
      However, I think the best way for you to understand
      the way it works is to try the game...
    </text>
  </chap>

  <chap title="Basic strategy">
    <text>
      When I play Liquid War, I always try to surround my opponents,
      and it usually works. 
    </text>
    <text>
      By the way, the computer has no strategy at all,
      he is a poor player, and if you get beaten by him,
      it means you have to improve yourself a lot!
    </text>
    <text>
      But still, the computer doesn't do one thing
      which I've seen many beginners doing:
      he never keeps his cursor motionless right in
      the middle of his own fighters,
      for this is the best way to loose.
    </text>
  </chap>

  <chap title="More strategy">
    <text>
       Here are some more tips, kindly submitted by Jan Samohyl.
    </text>
    <list>
      <elem>
         Try to cut your opponent off walls and surround him completely with
         your troops; when trying to  penetrate his forces inside a tunnel, keep
         your troops at the wall (and force them ocassionaly to attack off the
         wall). I think this is a biggest weakness of the computer AI, that it
         doesn't know this.
      </elem>
      <elem>
         When luring your troops to outflank an enemy, always move your cursor
         through the enemy, not the other way around.
      </elem>
      <elem>
         To penetrate very narrow tunnels, stand back for a while and let some
         enemy troops come from the tunnel to you. Then surround them, destroy,
         repeat.
      </elem>
      <elem>
         I have observed that with more than 2 players (6), the game difficulty
         depends on the map in the following way: If the playing field is
         completely empty, without any holes (topologically equivalent to full
         circle), the game is the easiest, because you can just go through the
         middle to outflank your opponent. If there is a single large obstacle
         (ie. playfield is topologically equivalent to ring (the area between two
         nested circles)), the game is the most difficult, because you have to
         choose one direction for the attack, and cannot simply defend the other
         direction. For other maps, it seems to really depend on their similarity
         to one of these two extreme situations (and army size, of course,
         because it changes the relative size of obstacles). Also, if you would
         later add another cursor, this property would probably disappear (maybe
         then games with n+1 obstacles would be the hardest ones with n cursors).
      </elem>
      <elem>
         If you want a particularly challenging computer game (at least for
         some maps), use several players, max out attack, min out defense, max
         out base health (opposite would be harder, but game then changes to the
         large cloud of black troops, so you don't see anything) and give winner
         an advantage.
      </elem>
    </list>
  </chap>

  <chap title="The winner is...">
    <text>
      The clever guy who has got the greatest number
      of fighters in his team at the end of the game.
      Or the one who exterminates all the other teams!
    </text>
  </chap>

</file>

=== bkil/liquid-war-5/doc/xml/platforms.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE file SYSTEM "file:xml/file.dtd">
<file title="Platform specific issues">

  <chap title="General remarks">
    <text>
      Liquid War is now a cross-platform game, thanks to Allegro.
      So now you can play under different OS.
    </text>
    <text>
      The same source tree will compile on all supported platforms, 
      but with slight differences when running. C preprocessor
      #defines are used to code some platform specific stuff,
      and in some cases there are different files for the
      DOS, Windows and UNIX versions.
    </text>
    <text>
      As I said, I try to use the same code for all platforms.
      This is in the long term the best choice.
      Otherwise there would different branches of the source tree,
      and I don't think this is a very good solution.
    </text>
    <text>
      Therefore some optimizations that were performed in the
      old DOS-only version have been totally removed, for they
      were 100% platform dependent (ie mode-X asm coding).
      So the new versions are all a little slower
      than the old 5.1 stuff, but the performance loss is only
      about 20%, which is not significant with today's PCs.
      And anyways the performance loss is most of the time limited
      to the goog old VGA 320x200x8 mode-X, which starts being
      kind of obsolete.
    </text>
  </chap>

  <chap title="DOS">
    <text>
      This is the original version.
      It's the fastest one as far as I know, the safest one and
      it will always be I think, since Allegro was first designed
      for DOS, and DOS allows a full unconditionnal access to all
      the hardware ressources LW requires.
      LW doesn't use any hardware
      acceleration and it's not been designed to do so.
      Unfortunately there's no network support for the DOS version
      of Liquid War.
    </text>
  </chap>

  <chap title="Windows">
    <text>
      When running under a Windows box, the DOS release used to be
      safer than the native Windows port. Now that DOS support is getting
      really poor with recent versions of Windows, the native Windows
      release of Liquid War starts begin the good choice for Windows users.
      And Allegro for Windows is getting quite stable in the 4.x series.
    </text>
    <text>
      The other reason to choose this release rather than the DOS release
      is that it has network support.
    </text>
    <text>
      If you have problems running Liquid War under Windows, please check out
      the "data\lwwin.log" file which should be written each time you run the game.
      It contains the information which is displayed on the console under
      other platforms, and might give you a clue about what's going wrong.
    </text>
  </chap>

  <chap title="GNU/Linux">
    <text>
      This port is the most recent one, and also the one I prefer.
      Paths have been changed to an UNIXish style,
      ie the data is stored in:
    </text>
    <code>
      /usr/local/share/games/liquidwar
    </code>
    <text>
      the executable in:
    </text>
    <code>
      /usr/local/games
    </code>
    <text>
      and the configuration file is
    </text>
    <code>
      ~/.liquidwarrc
    </code>
    <text>
      Since not all GNU/Linux distributions have /usr/local/games in their path,
      I also put a symbolic link to the binaries in /usr/local/bin.
      I believe Liquid War is quite FHS compliant, so if its default
      directories do not match your configuration, blame your distro
      for not following the standards 8-) AFAIK the only touchy
      directory is /usr/local/share/pixmaps which I've seen on many distribution
      but does not seem to be referenced in the FHS.
    </text>
    <text>
      With the latest releases of Allegro, Liquid War is becoming pretty
      stable under GNU/Linux. You should also know that the GNU/Linux port is usually
      the most up to date, since I very very seldom boot Windows at home
      and do most of the coding under GNU/Linux.
    </text>
  </chap>

  <chap title="FreeBSD">
    <text>
      This is the latest port, so I expect it to be a little touchy to
      install and/or run for some time.
    </text>
    <text>
      Note that to compile the game you'll need to install GNU tools like
      gmake and gcc. Liquid War won't compile with the genuine make and cc
      commands.
    </text>
    <text>
      One thing you might ask is: "why do you provide the binary as a plain
      .tgz file, it would be much nicer if a standard FreeBSD port was 
      provided instead!". The answer is that the statically linked binary
      should work flawlessly and does not raise any dependency problem.
      Also I don't know how to make a BSD port
      and I'm not really interested in doing it. If it's easy to do, then someone
      can simply do it and send it back to me. If it's hard to do, then I do not
      really have the time nor motivation to do it. What I did is make the
      code and install scripts FreeBSD friendly so that it would be possible to
      compile the game under FreeBSD. Packaging is another story. 
    </text>
  </chap>

  <chap title="Mac OS X">
    <text>
      There's currently a beta version of a Mac OS X port for Liquid War.
      Ryan D. Brown nicely managed to compile and run the game under Mac OS X,
      and the latest news was that it does basically work. Still, this port
      did not go through intensive testing, so there might still be some bugs,
      expecially concerning networking.
    </text>
    <text>
      There were some byte endianess problems in previous ( &lt;=5.5.8 ) 
      releases of LW, but I tried to fix them and they should be gone now.
    </text>
    <text>
      As of today, we're trying to find out a convenient way to package and
      release the Mac OS X version of LW. You can contact us on the
      mailing list if you're interested in this port.
    </text>
  </chap>

  <chap title="GP2X">
    <text>
      Liquid War has been ported to the GP2X handheld gaming platform, thanks
      to the fact George Foot ported Allegro to this platform.
      More informations on "http://www.glost.eclipse.co.uk/gfoot/gp2x/allegro.html"
    </text>
    <text>
      FYI, Allegro 4.2.0 needed a trivial patch which is in the ./misc directory
      of the source LW distribution and adds src/misc/colconv.c to the list of needed
      files, and was compiled with the following options:
    </text>
    <code>
./configure --prefix=$GP2X_USER_PREFIX --build=x86_64-pc-linux-gnu --host=arm-open2x-linux --enable-lgp2x=$GP2X_SYSTEM_PREFIX
    </code>
    <text>
      It might also be necessary to run make then make install the make and make install 
      again since library detection is weird in cross-platform environments.
    </text>
  </chap>
</file>

=== bkil/liquid-war-5/doc/xml/todo.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE file SYSTEM "file:xml/file.dtd">
<file title="To do">

  <chap title="Bug-fixing">
    <text>
      In its latest releases Liquid War is quite stable IMHO. 
      However there are still some issues with network under Windows
      for instance. I'm aware of these bugs and I'm trying to fix them
      but this does really take time.
    </text>
    <text>
      I always welcome bug-reports and patches, as making Liquid War W 5.x.x as
      stable and bug-free as possible is really important to me - and
      most of the time players also appreciate stable programs 8-)
    </text>
  </chap>
  
  <chap title="Artwork">
    <text>
      It's hard to find people to do that kind of thing.
      Artists are indeed pretty rare, at least artists who wish to
      create stuff freely...
      So if you feel like adding some theme support to Liquid War,
      this could *really* help.
      I used the textures I had but it would be nice
      if one could have a "space" ambiance, an "ocean" ambiance
      or a "desert" ambiance.
      This could really make the game better I think.
    </text>
    <text>
      Musics (in midi format) are also appreciated.
      Tim Chadburn spontaneously contributed the first midi files,
      and it really pleased me 8-)
    </text>
  </chap>

  <chap title="New features">
    <text>
      I regularly receive requests for new features in Liquid War.
      Of course I do not have enough time to implement them all,
      so they land in my "todo" list. However, most "major"
      evolutions are now planned for Liquid War 6, since the code
      in Liquid War 5 is bloated as hell. It's all right to
      debug it and code minor evolutions, but that's all.
    </text>
    <text>
      However, here's a list of what "could be" in the next
      Liquid War 5.x.x releases, although it might never be
      implemented there and come later with Liquid War 6:
    </text>
    <list>
      <elem>
	Network enhancements. Network in LW5 is somewhat buggy and
	hard to use, improvements wouldn't harm.
      </elem>
      <elem>
	Theme support. This would be a way to get rid of the ugly
	current fonts and menus.
      </elem>
    </list>
  </chap>

  <chap title="Liquid War 6">
    <text>
      Since summer 2005, Liquid War 6, a complete rewrite of Liquid War,
      is on its way. See 
      "http://www.ufoot.org/liquidwar/v6" 
      for more informations.
    </text>
  </chap>

</file>

=== bkil/liquid-war-5/doc/xml/fanfic.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE file SYSTEM "file.dtd">
<file title="Fanfic">
  <chap title="What's this?">
    <text>
      Quoting Gavin: "I wrote a liquid war fanfic some time ago [...] I wrote it after a friend claimed that there wasn't any liquid war fanfic because it wasn't possible."
    </text>
    <text>
      So here it is, a Liquid War fanfic, enjoy! (and special thanks to Gavin)
    </text>
  </chap>

  <chap title="The Battle of Emberlificoted">
    <part title="...">
      <text>
The General presided over his massing army in his seat, or rather hovering ring, of power. It dipped slightly as he flew low over his troops marching through the viscous marsh-like terrain. They were like children: obedient, loyal, and they ate a lot.
      </text>
      <text>
Glancing at the status panel mounted in front of him he grimaced; the other five armies: Yellow, Green, Orange, Turquoise, and, of course, Red, were also readying armies of a similar size to his own. His violet clones would have to fight hard and eat well to win this day.
      </text>
      <text>
Today would not be a battle of luck, the General mused, it would be a battle of tactics, of alliances, and of betrayal. Every clone was identical - that was the general idea behind clones - and the terrain seemed strangely symmetrical; it would not give advantage to any of the six armies amassed today. Glancing at the hologram of the battlefield projected in front of him the General noted that he would have to move quickly, Orange and Yellow were too close for comfort, though fortunately Baron Red's army of eponymous coloured clones was the furthest.
      </text>
      <text>
General Violet's fingertips were sweaty even before they touched the four main control keys in front of him. They were labeled 'W', 'A', 'D', and, of course, the full retreat button - very useful for misleading foes and ambushing them as they pursued - 'S'. The keys were arrange in a roughly equilateral triangular pattern; with 'S' forming the base and being adjacent to both 'A' and 'D', 'W' formed the tip of the triangle.
      </text>
      <text>
A long breath left his parched lips as at last he made his move.
      </text>
    </part>
    <part title="...">
      <text>
"Dammit!" he screamed moments later. He had misjudged Captain Yellow and Commander Orange; he had expected one at least to attack immediately, one he could have handled. They were working together - foiling his attempt to shoot between them to near the center of the battlefield to gain a better vantage point. Yellow had shot down towards him, cutting off his advance, and now Orange had sealed his escape route. "It's not over yet" muttered the General. He opened a voice channel with Commander Orange:
      </text>
      <text>
"Very clever. Flawed, but still clever."
      </text>
      <text>
"Flawed?" came the reply.
      </text>
      <text>
"Yes flawed, when the good Captain is finished devouring my army who do you think he will turn to next?", bluffed the General - his hands worked quickly as he manoeuvred his hovering control ring, all that his troops ever saw of him, carefully towards the weakest section of his attackers. If he could just break out a few units he could soon turn the tide against both Yellow and Orange.
      </text>
      <text>
"We have an alliance..." Orange's voice was unsure now.
      </text>
      <text>
Time for some sarcasm to through her even more off balance, thought the General,      
      </text>
      <text>
"I gathered", he spoke softly, slowly, and with too much meaning. Then closing the channel he turned his attention back to his escape.
      </text>
    </part>
    <part title="...">
      <text>
"Yes!" wooped the ecstatic figure of the General. Fifty or so of his troops had broken free undetected and were even now working their way cautiously towards the camps of the Yellow army, only the front lines were still actively fighting; this opening gambit of Yellow and Orange had turned into a stale siege and Yellow's army had pitched tent.
      </text>
      <text>
General Violet steered his hovering guidance ring to the center of the Yellow camp. His troops struck, both those who had got behind the lines and those who were still besieged. Yellow reacted too slowly and suddenly found that her army, was shrinking back from the onslaught. There was nowhere to run to, and bye now her only ally - Commander Orange - had abandoned her to her fate; he was too busy engaging Sir. Turquoise, who had managed to escape from the slaughter that the Baron had caused to the Turquoise ranks and was even now valiantly attacking the flanks of the Orange troops.
      </text>
      <text>
A glance at the status panel showed that Yellow's life force was fading quickly: 8%, 3%, 1%, Gone.
      </text>
      <text>
The General smiled, he always enjoyed getting the first kill, and by now his armies life force had grown and his clones had replicated. With his, now, formidable fighting force it was no problem to engulf both Sir. Turquoise and Commander Orange's brawling armies and annihilate them. Once again his army grew in size and power. Now if only the Baron didn't notice that..., thought the General.
      </text>
    </part>
    <part title="...">
      <text>
"Too late!" yelped the General, now thrown into panic, as he saw the approaching Baron. His army had also grown in size and power - having fatally injured the Turquoise army within the opening moments of the battle, and having finally managed to catch the elusive fleeing form of, or what remained of, Emperor Green.
      </text>
      <text>
Gripping the controls harder the General thought quickly, his army doesn't so completely outnumber me that this is already over, however unless I can cause him to make a mistake that allows me to take the upper hand then I will inevitably lose. Maybe I can...
      </text>
      <text>
This thought was terminated and replaced by another as the Baron's angry red troops broke through the undergrowth that had covered their movements and started to surround the General's army. The thought that now throbbed through the panic-stricken mind of General Violet was simply 'Run!'.
      </text>
      <text>
Even as he signaled the retreat and made for what seemed to be the only possible means of escape the Baron's blood red control ring appeared at the opening. The General knew it was over, even before the host of red beings appeared at the opening.
      </text>
      <text>
There was no escape. His life force was almost depleted and he was surrounded. Then it was that the Baron decided to communicate:
      </text>
      <text>
"Too bad. It was a good game"
      </text>
      <text>
The General blinked, gaped, and was generally gobsmacked. Just before his life force completely failed and his own weary eyes closed in defeat he snarled,
      </text>
      <text>
"What!? This is not a game!" were the General's dying words.
      </text>
    </part>
  </chap>
</file>
